# Reconstruction configuration file

defaults:
  - encoder: vgg19
  - generator: relu7generator

decoded_features:
  name: ArtificialShapes

  path: ./data/ArtificialShapes/derivatives/decoded_features/deeprecon_fmriprep_rep5_500voxel_allunits_fastl2lir_alpha100/decoded_features/caffe/VGG_ILSVRC_19_layers
  subjects:
    - Sub1
  rois:
    - VC
  decoders:
    path: ./data/contents_shared/ImageNetTraining/derivatives/feature_decoders/deeprecon_fmriprep_rep5_trainave_500voxel_allunits_fastl2lir_alpha100/caffe/VGG_ILSVRC_19_layers



icnn:
  num_iteration: 1000
  feature_scaling: feature_std_train_mean_center

output:
  path: ./data/ArtificialShapes/derivatives/reconstruction/icnn/${_analysis_name_}_${encoder.name}_${generator.name}_gd_scaling_${icnn.feature_scaling}_${icnn.num_iteration}iter/decoded/${decoded_features.name}
  prefix: recon_image-
  ext: tiff

evaluation:
  true_image:
    path: ./data/ArtificialShapes/source
    ext: JPEG
