# Reconstruction configuration file

# Feature decoding settings ##################################################

feature decoding:
  /home/nu/mtanaka/project/dnn_test/recon_repro2023/recon-repro/diffusion_feature-decoding/Brain_Diffuser/config/deeprecon_testArtificialShapes_trainnoave_testave_fastl2lir_alpha_100000_versatile_diffusion.yaml
  
# True images ################################################################

true image dir:
  /home/nu/data/contents_shared/ArtificialShapes/source

true image ext:
  tiff

# Subject/ROI settings for reconstruction ####################################

recon subjects:
  - dr-01
  - dr-02
  - dr-03
  - dr-04

recon rois:
  - VC

# Versatile diffusion reconstruction ########################################################

vd local path:
  ./versatile_diffusion

seed:
  0

scaled decoded feature:
  true

recon output dir:
  /home/nu/data/contents_shared/ArtificialShapes/derivatives/reconstruction/versatile_diffusion/vd_doublecond_scaled_pytorch/decoded

recon image ext:
  tiff

recon image prefix:
  recon_image-
  
seed image dir:
  /home/nu/data/contents_shared/ArtificialShapes/derivatives/reconstruction/vdvae/vdvae_decoder_top31layers_scaled_pytorch/decoded/deeprecon_testArtificialShapes_trainnoave_testave_fastl2lir_alpha_50000
  
seed image prefix:
  recon_image-
  
seed image ext:
  tiff

recon figure dir:
  /home/nu/data/contents_shared/ArtificialShapes/derivatives/figures/reconstruction/versatile_diffusion/vd_doublecond_scaled_pytorch/decoded

recon eval encoder:
  AlexNet
