# Reconstruction configuration file

defaults:
  - encoder: vgg19
  - generator: relu7generator

decoded_features:
  name: ArtificialShapes

  #path: /home/nu/data/contents_shared/ArtificialShapes/derivatives/decoded_features/deeprecon_fmriprep_rep5_500voxel_allunits_fastl2lir_alpha100/decoded_features/caffe/VGG_ILSVRC_19_layers
  model_name: caffe/VGG_ILSVRC_19_layers
  decoder_setting: deeprecon_fmriprep_rep5_500voxel_allunits_fastl2lir_alpha100

  subjects:
    - TH
  rois:
    - VC
  training_dataset: ImageNetTraining
  #decoders:
  #  path: /home/nu/data/contents_shared/ImageNetTraining/derivatives/feature_decoders/deeprecon_fmriprep_rep5_trainave_500voxel_allunits_fastl2lir_alpha100/caffe/VGG_ILSVRC_19_layers



icnn:
  num_iteration: 800
  feature_scaling: feature_std_train_mean_center

output:
  path: ./results/reconstruction/ArtificialShapes/derivatives/reconstruction/icnn/${_analysis_name_}_${encoder.name}_${generator.name}_gd_scaling_${icnn.feature_scaling}_${icnn.num_iteration}iter/decoded/${decoded_features.name}
  prefix: recon_image-
  ext: tiff

evaluation:
  true_image:
    path: ./data/ArtificialShapes/source
    ext: tiff

target_images:
  - colorExpStim01_red_square
  - colorExpStim03_red_largering
  - colorExpStim04_red_+
  - colorExpStim09_green_+
  - colorExpStim31_white_square
  - colorExpStim40_black_X