# Reconstruction configuration file

defaults:
  - encoder: vgg19
  - generator: relu7generator

decoded_features:
  name: NSD

  path: ./data/NSD-stimuli/derivatives/decoded_features/nsd-37ses_func1pt8mm_betas_fithrf_GLMdenoise_RR_testshared1000_trainnoave_testave_fastl2lir_a100/decoded_features/caffe/VGG_ILSVRC_19_layers
  subjects:
    - nsd-01
  rois:
    - nsdgeneral
  decoders:
    path: ./data/contents_shared/NSD-stimuli/derivatives/feature_decoders/nsd-37ses_func1pt8mm_betas_fithrf_GLMdenoise_RR_testshared1000_trainnoave_testave_fastl2lir_a100/caffe/VGG_ILSVRC_19_layers



icnn:
  num_iteration: 1000
  feature_scaling: feature_std_train_mean_center

output:
  path: ./data/NSD-stimuli/derivatives/reconstruction/icnn/${_run.name}_${encoder.name}_${generator.name}_gd_scaling_${icnn.feature_scaling}_${icnn.num_iteration}iter/decoded/${decoded_features.name}
  prefix: recon_image-
  ext: tiff

evaluation:
  true_image:
    path: ./data/NSD-stimuli/source
    ext: png
