# Reconstruction configuration file

# Feature decoding settings ##################################################

feature dir: # feature decdoingではないので注意, true feature directoryを直接指定
  /home/nu/data/contents_shared/NSD-stimuli/derivatives/features/pytorch/brain_diffuser_versatile_diffusion
  
# True images ################################################################

true image dir:
  /home/nu/data/contents_shared/NSD-stimuli/source

true image ext:
  png

# recon_subjects, recon_roisは設定しない

# Reconstruction ########################################################

vd local path:
  ./versatile_diffusion

seed:
  0

#seed image dir, seed image prefix, seed image ext を設定しないと自動的にseed imageなしの再構成になる

recon output dir:
  ../../derivatives/NSD-stimuli/derivatives/reconstruction/versatile_diffusion/vd_doublecond_novdvae_pytorch_var_mix/true

recon image ext:
  tiff

recon image prefix:
  recon_image-

recon figure dir:
  /home/nu/data/contents_shared/NSD-stimuli/derivatives/figures/reconstruction/vdvae/vdvae_decoder_top31layers_scaled_pytorch/decoded

recon eval encoder:
  AlexNet

recon targets:
  - nsd03050
  - nsd10065
  - nsd14611
  - nsd19201
  - nsd26436
  - nsd32308
  - nsd37802
  - nsd67803

mix cond:
  1.0

ddim step:
  50
